"""Added status column to Budget model

Revision ID: 004e1403feba
Revises: 92e2f3d38084
Create Date: 2025-03-10 17:23:16.303438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '004e1403feba'
down_revision = '92e2f3d38084'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # Set a default value for existing rows
    op.execute("UPDATE budgets SET status = 'draft' WHERE status IS NULL;")

    # Alter the column to be NOT NULL after default values are set
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=20), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_budget_name', type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
