"""updated budget model

Revision ID: 02993ea68498
Revises: a44e5f722d86
Create Date: 2025-03-02 20:38:22.410229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02993ea68498'
down_revision = 'a44e5f722d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_withholding', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('retirement_contribution', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benefit_deductions', sa.Float(), nullable=True))
        batch_op.drop_constraint('budgets_profile_id_fkey', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('profile_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('gross_income_frequency')
        batch_op.drop_column('other_income_sources')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_income_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gross_income_frequency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('budgets_profile_id_fkey', 'profiles', ['profile_id'], ['id'])
        batch_op.drop_column('benefit_deductions')
        batch_op.drop_column('retirement_contribution')
        batch_op.drop_column('tax_withholding')

    # ### end Alembic commands ###
