"""Revert salary_type back to income_type

Revision ID: 92e2f3d38084
Revises: 62de457c6546
Create Date: 2025-03-08 17:59:30.203204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e2f3d38084'
down_revision = '62de457c6546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_type', sa.String(length=20), nullable=False))
        batch_op.drop_column('salary_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('income_type')

    # ### end Alembic commands ###
